CREATE TABLE IF NOT EXISTS eat_user (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    phone       VARCHAR(50)  NOT NULL UNIQUE COMMENT '手机号AES加密存储',
    nickname    VARCHAR(50)  DEFAULT '' COMMENT '用户昵称',
    avatar_url  VARCHAR(255) DEFAULT '' COMMENT '头像URL',
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
